version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/weatherassignment
permissions:
  - object: /var/www/weatherassignment
    owner: ec2-user
    group: ec2-user
 # AfterInstall:
 #    - location: script/AfterInstall.sh
 #      runas: ec2-user
 #  ApplicationStart:
 #    - location: script/ApplicationStart.sh
 #      runas: ec2-user