version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/weatherassignment
permissions:
  - object: /var/www/weatherassignment
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/afterInstall.sh
  ApplicationStart:
    - location: scripts/applicationStart.sh