version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/weatherassignment
permissions:
  - object: /var/www/weatherassignment
    owner: ubuntu
    group: ubuntu
hooks:
   AfterInstall:
     - location: scripts/afterInstall.sh
   ApplicationStart:
     - location: scripts/applicationStart.sh
       runas: ubuntu